spring:
  jackson:
    #设置对输出参数的格式化
    date-format: yyyy-MM-dd HH:mm:ss
    #北京时间相对伦敦有8个小时时差所以使用GMT+8，这样才能正常显示日期
    time-zone: GMT+8
  mvc:
    #设置对输入参数的格式化，这样后台的接口就可以接收Date类型
    date-format: yyyy-MM-dd
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/phone?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl